// import { Module } from '@nestjs/common';
// import { TypeOrmModule } from '@nestjs/typeorm';
// import { atributosController } from './metrofrenos.controller';
// import { citasController } from './metrofrenos.controller';
// import { clavesController } from './metrofrenos.controller';
// import { coleccionesController } from './metrofrenos.controller';
// import { configController } from './metrofrenos.controller';
// import { config_autogestionController } from './metrofrenos.controller';
// import { config_bdController } from './metrofrenos.controller';
// import { config_cabezaController } from './metrofrenos.controller';
// import { config_capturaController } from './metrofrenos.controller';
// import { config_captura_detController } from './metrofrenos.controller';
// import { config_cotizaController } from './metrofrenos.controller';
// import { config_detalleController } from './metrofrenos.controller';
// import { config_documentoController } from './metrofrenos.controller';
// import { config_formularioController } from './metrofrenos.controller';
// import { config_kardexController } from './metrofrenos.controller';
// import { config_qrController } from './metrofrenos.controller';
// import { config_qr_detController } from './metrofrenos.controller';
// import { config_relController } from './metrofrenos.controller';
// import { config_tableController } from './metrofrenos.controller';
// import { config_targetaController } from './metrofrenos.controller';
// import { config_ubicacionController } from './metrofrenos.controller';
// import { config_vistaController } from './metrofrenos.controller';
// import { config_vistatController } from './metrofrenos.controller';
// import { config_zonasController } from './metrofrenos.controller';
// import { config_citasController } from './metrofrenos.controller';
// import { config_encuestaController } from './metrofrenos.controller';
// import { contenidosController } from './metrofrenos.controller';
// import { contenidos_capController } from './metrofrenos.controller';
// import { contenidos_detController } from './metrofrenos.controller';
// import { contenidos_proController } from './metrofrenos.controller';
// import { contenidos_recController } from './metrofrenos.controller';
// import { contenidos_subController } from './metrofrenos.controller';
// import { contenidos_tskController } from './metrofrenos.controller';
// import { contenidos_usrController } from './metrofrenos.controller';
// import { cuestionariosController } from './metrofrenos.controller';
// import { cuestionarios_pController } from './metrofrenos.controller';
// import { cuestionarios_rController } from './metrofrenos.controller';
// import { dep_equiposController } from './metrofrenos.controller';
// import { detalle_celdasController } from './metrofrenos.controller';
// import { dtn_tiempoController } from './metrofrenos.controller';
// import { encuestaController } from './metrofrenos.controller';
// import { mercadoController } from './metrofrenos.controller';
// import { mercado_detController } from './metrofrenos.controller';
// import { nichosController } from './metrofrenos.controller';
// import { oreparacion1_2000Controller } from './metrofrenos.controller';
// import { oreparacion2_2000Controller } from './metrofrenos.controller';
// import { preguntasController } from './metrofrenos.controller';
// import { presupuestosController } from './metrofrenos.controller';
// import { sys_appsController } from './metrofrenos.controller';
// import { sys_rolesController } from './metrofrenos.controller';
// import { sys_rol_campoController } from './metrofrenos.controller';
// import { sys_submenusController } from './metrofrenos.controller';
// import { tablasController } from './metrofrenos.controller';
// import { tablas_detController } from './metrofrenos.controller';
// import { temporadasController } from './metrofrenos.controller';
// import { vencimientosController } from './metrofrenos.controller';
// import { versionesController } from './metrofrenos.controller';
// import { versiones_detController } from './metrofrenos.controller';
// import { zonasController } from './metrofrenos.controller';
// import { categoriasController } from './metrofrenos.controller';
// import { celdasController } from './metrofrenos.controller';
// import { clientesController } from './metrofrenos.controller';
// import { conceptosController } from './metrofrenos.controller';
// import { consecutivosController } from './metrofrenos.controller';
// import { datos_importadosController } from './metrofrenos.controller';
// import { empresasController } from './metrofrenos.controller';
// import { grupos_usuariosController } from './metrofrenos.controller';
// import { kardexController } from './metrofrenos.controller';
// import { motivosController } from './metrofrenos.controller';
// import { motivos_anulacionController } from './metrofrenos.controller';
// import { novimientosController } from './metrofrenos.controller';
// import { novimientos_docController } from './metrofrenos.controller';
// import { novimientos_vehController } from './metrofrenos.controller';
// import { pedidosController } from './metrofrenos.controller';
// import { pedidos_detController } from './metrofrenos.controller';
// import { romboController } from './metrofrenos.controller';
// import { see_costo_kwhController } from './metrofrenos.controller';
// import { see_datosController } from './metrofrenos.controller';
// import { see_formulasController } from './metrofrenos.controller';
// import { see_medicionesController } from './metrofrenos.controller';
// import { see_periodosController } from './metrofrenos.controller';
// import { see_temperaturaController } from './metrofrenos.controller';
// import { see_temperatura_detController } from './metrofrenos.controller';
// import { see_variablesController } from './metrofrenos.controller';
// import { see_variables_detController } from './metrofrenos.controller';
// import { serviciosController } from './metrofrenos.controller';
// import { subcategoriasController } from './metrofrenos.controller';
// import { sucurralesController } from './metrofrenos.controller';
// import { susuariosController } from './metrofrenos.controller';
// import { tecnicosController } from './metrofrenos.controller';
// import { tra_categoriasController } from './metrofrenos.controller';
// import { tra_cilindrajeController } from './metrofrenos.controller';
// import { tra_cotizacionController } from './metrofrenos.controller';
// import { tra_cotizacion_detController } from './metrofrenos.controller';
// import { tra_cotizacion_totController } from './metrofrenos.controller';
// import { tra_detallesController } from './metrofrenos.controller';
// import { tra_fisicoController } from './metrofrenos.controller';
// import { tra_grupposController } from './metrofrenos.controller';
// import { tra_marcasController } from './metrofrenos.controller';
// import { tra_matriculasController } from './metrofrenos.controller';
// import { tra_matriculas_carController } from './metrofrenos.controller';
// import { tra_matriculas_detController } from './metrofrenos.controller';
// import { tra_modelosController } from './metrofrenos.controller';
// import { tra_movtosController } from './metrofrenos.controller';
// import { tra_movtos_detController } from './metrofrenos.controller';
// import { tra_movtos_totController } from './metrofrenos.controller';
// import { tra_partesController } from './metrofrenos.controller';
// import { tra_periodosController } from './metrofrenos.controller';
// import { tra_plantillasController } from './metrofrenos.controller';
// import { tra_plantillas_detController } from './metrofrenos.controller';
// import { tra_posicionesController } from './metrofrenos.controller';
// import { tra_procesosController } from './metrofrenos.controller';
// import { tra_procesos_tiemposController } from './metrofrenos.controller';
// import { tra_procesos_tiempos_coloresController } from './metrofrenos.controller';
// import { tra_referenciasController } from './metrofrenos.controller';
// import { tra_referencias_proveedorController } from './metrofrenos.controller';
// import { tra_saldosController } from './metrofrenos.controller';
// import { tra_sjustesController } from './metrofrenos.controller';
// import { tra_tipo_motorController } from './metrofrenos.controller';
// import { tra_tipos_vehController } from './metrofrenos.controller';
// import { tra_ubicacionesController } from './metrofrenos.controller';
// import { usuariosController } from './metrofrenos.controller';
// import { usuarios1Controller } from './metrofrenos.controller';
// import { vehiculosController } from './metrofrenos.controller';

// // Importar entidades
// import {
//   CITAS,
//   CLAVES,
//   COLECCIONES,
//   CONFIG,
//   CONFIG_AUTOGESTION,
//   CONFIG_BD,
//   CONFIG_CABEZA,
//   CONFIG_CAPTURA,
//   CONFIG_CAPTURA_DET,
//   CONFIG_COTIZA,
//   CONFIG_DETALLE,
//   CONFIG_DOCUMENTO,
//   CONFIG_FORMULARIO,
//   CONFIG_KARDEX,
//   CONFIG_QR,
//   CONFIG_QR_DET,
//   CONFIG_REL,
//   CONFIG_TABLE,
//   CONFIG_TARGETA,
//   CONFIG_UBICACION,
//   CONFIG_VISTA,
//   CONFIG_VISTAT,
//   CONFIG_ZONAS,
//   CONFIG_CITAS,
//   CONFIG_ENCUESTA,
//   CONTENIDOS,
//   CONTENIDOS_CAP,
//   CONTENIDOS_DET,
//   CONTENIDOS_PRO,
//   CONTENIDOS_REC,
//   CONTENIDOS_SUB,
//   CONTENIDOS_TSK,
//   CONTENIDOS_USR,
//   CUESTIONARIOS,
//   CUESTIONARIOS_P,
//   CUESTIONARIOS_R,
//   DEP_EQUIPOS,
//   DETALLE_CELDAS,
//   DTN_TIEMPO,
//   ENCUESTA,
//   MERCADO,
//   MERCADO_DET,
//   NICHOS,
//   OREPARACION1_2000,
//   OREPARACION2_2000,
//   PREGUNTAS,
//   PRESUPUESTOS,
//   SYS_APPS,
//   SYS_ROLES,
//   SYS_ROL_CAMPO,
//   SYS_SUBMENUS,
//   TABLAS,
//   TABLAS_DET,
//   TEMPORADAS,
//   VENCIMIENTOS,
//   VERSIONES,
//   VERSIONES_DET,
//   ZONAS,
//   categorias,
//   celdas,
//   clientes,
//   conceptos,
//   consecutivos,
//   datos_importados,
//   empresas,
//   grupos_usuarios,
//   kardex,
//   motivos,
//   motivos_anulacion,
//   novimientos,
//   novimientos_doc,
//   novimientos_veh,
//   pedidos,
//   pedidos_det,
//   rombo,
//   see_costo_kwh,
//   see_datos,
//   see_formulas,
//   see_mediciones,
//   see_periodos,
//   see_temperatura,
//   see_temperatura_det,
//   see_variables,
//   see_variables_det,
//   servicios,
//   subcategorias,
//   sucurrales,
//   susuarios,
//   tecnicos,
//   tra_categorias,
//   tra_cilindraje,
//   tra_cotizacion,
//   tra_cotizacion_det,
//   tra_cotizacion_tot,
//   tra_detalles,
//   tra_fisico,
//   tra_gruppos,
//   tra_marcas,
//   tra_matriculas,
//   tra_matriculas_car,
//   tra_matriculas_det,
//   tra_modelos,
//   tra_movtos,
//   tra_movtos_det,
//   tra_movtos_tot,
//   tra_partes,
//   tra_periodos,
//   tra_plantillas,
//   tra_plantillas_det,
//   tra_posiciones,
//   tra_procesos,
//   tra_procesos_tiempos,
//   tra_procesos_tiempos_colores,
//   tra_referencias,
//   tra_referencias_proveedor,
//   tra_saldos,
//   tra_sjustes,
//   tra_tipo_motor,
//   tra_tipos_veh,
//   tra_ubicaciones,
//   usuarios,
//   usuarios1,
//   vehiculos
// } from './entities/metrofrenos.entity';

// // Importar servicios
// import {
//   ATRIBUTOSService,
//   CITASService,
//   CLAVESService,
//   COLECCIONESService,
//   CONFIGService,
//   CONFIGAUTOGESTIONService,
//   CONFIGBDService,
//   CONFIGCABEZAService,
//   CONFIGCAPTURAService,
//   CONFIGCAPTURADETService,
//   CONFIGCOTIZAService,
//   CONFIGDETALLEService,
//   CONFIGDOCUMENTOService,
//   CONFIGFORMULARIOService,
//   CONFIGKARDEXService,
//   CONFIGQRService,
//   CONFIGQRDETService,
//   CONFIGRELService,
//   CONFIGTABLEService,
//   CONFIGTARGETAService,
//   CONFIGUBICACIONService,
//   CONFIGVISTAService,
//   CONFIGVISTATService,
//   CONFIGZONASService,
//   CONFIG_CITASService,
//   CONFIG_ENCUESTAService,
//   CONTENIDOSService,
//   CONTENIDOS_CAPService,
//   CONTENIDOS_DETService,
//   CONTENIDOS_PROService,
//   CONTENIDOS_RECService,
//   CONTENIDOS_SUBService,
//   CONTENIDOS_TSKService,
//   CONTENIDOS_USRService,
//   CUESTIONARIOSService,
//   CUESTIONARIOS_PService,
//   CUESTIONARIOS_RService,
//   DEP_EQUIPOSService,
//   DETALLE_CELDASService,
//   DTN_TIEMPOService,
//   ENCUESTAService,
//   MERCADOService,
//   MERCADO_DETService,
//   NICHOSService,
//   OREPARACION1_2000Service,
//   OREPARACION2_2000Service,
//   PREGUNTASService,
//   PRESUPUESTOSService,
//   SYS_APPSService,
//   SYS_ROLESService,
//   SYS_ROL_CAMPOService,
//   SYS_SUBMENUSService,
//   TABLASService,
//   TABLAS_DETService,
//   TEMPORADASService,
//   VENCIMIENTOSService,
//   VERSIONESService,
//   VERSIONESDETService,
//   ZONASService,
//   categoriasService,
//   celdasService,
//   clientesService,
//   conceptosService,
//   consecutivosService,
//   datos_importadosService,
//   empresasService,
//   grupos_usuariosService,
//   kardexService,
//   motivosService,
//   motivos_anulacionService,
//   novimientosService,
//   novimientos_docService,
//   novimientos_vehService,
//   pedidosService,
//   pedidos_detService,
//   romboService,
//   see_costo_kwhService,
//   see_datosService,
//   see_formulasService,
//   see_medicionesService,
//   see_periodosService,
//   see_temperaturaService,
//   see_temperatura_detService,
//   see_variablesService,
//   see_variables_detService,
//   serviciosService,
//   subcategoriasService,
//   sucurralesService,
//   susuariosService,
//   tecnicosService,
//   tra_categoriasService,
//   tra_cilindrajeService,
//   tra_cotizacionService,
//   tra_cotizacion_detService,
//   tra_cotizacion_totService,
//   tra_detallesService,
//   tra_fisicoService,
//   tra_grupposService,
//   tra_marcasService,
//   tra_matriculasService,
//   tra_matriculas_carService,
//   tra_matriculas_detService,
//   tra_modelosService,
//   tra_movtosService,
//   tra_movtos_detService,
//   tra_movtos_totService,
//   tra_partesService,
//   tra_periodosService,
//   tra_plantillasService,
//   tra_plantillas_detService,
//   tra_posicionesService,
//   tra_procesosService,
//   tra_procesos_tiemposService,
//   tra_procesos_tiempos_coloresService,
//   tra_referenciasService,
//   tra_referencias_proveedorService,
//   tra_saldosService,
//   tra_sjustesService,
//   tra_tipo_motorService,
//   tra_tipos_vehService,
//   tra_ubicacionesService,
//   usuariosService,
//   usuarios1Service,
//   vehiculosService
// } from './metrofrenos.service';

// @Module({
//   controllers: [
//     atributosController,
//     citasController,
//     clavesController,
//     coleccionesController,
//     configController,
//     config_autogestionController,
//     config_bdController,
//     config_cabezaController,
//     config_capturaController,
//     config_captura_detController,
//     config_cotizaController,
//     config_detalleController,
//     config_documentoController,
//     config_formularioController,
//     config_kardexController,
//     config_qrController,
//     config_qr_detController,
//     config_relController,
//     config_tableController,
//     config_targetaController,
//     config_ubicacionController,
//     config_vistaController,
//     config_vistatController,
//     config_zonasController,
//     config_citasController,
//     config_encuestaController,
//     contenidosController,
//     contenidos_capController,
//     contenidos_detController,
//     contenidos_proController,
//     contenidos_recController,
//     contenidos_subController,
//     contenidos_tskController,
//     contenidos_usrController,
//     cuestionariosController,
//     cuestionarios_pController,
//     cuestionarios_rController,
//     dep_equiposController,
//     detalle_celdasController,
//     dtn_tiempoController,
//     encuestaController,
//     mercadoController,
//     mercado_detController,
//     nichosController,
//     oreparacion1_2000Controller,
//     oreparacion2_2000Controller,
//     preguntasController,
//     presupuestosController,
//     sys_appsController,
//     sys_rolesController,
//     sys_rol_campoController,
//     sys_submenusController,
//     tablasController,
//     tablas_detController,
//     temporadasController,
//     vencimientosController,
//     versionesController,
//     versiones_detController,
//     zonasController,
//     categoriasController,
//     celdasController,
//     clientesController,
//     conceptosController,
//     consecutivosController,
//     datos_importadosController,
//     empresasController,
//     grupos_usuariosController,
//     kardexController,
//     motivosController,
//     motivos_anulacionController,
//     novimientosController,
//     novimientos_docController,
//     novimientos_vehController,
//     pedidosController,
//     pedidos_detController,
//     romboController,
//     see_costo_kwhController,
//     see_datosController,
//     see_formulasController,
//     see_medicionesController,
//     see_periodosController,
//     see_temperaturaController,
//     see_temperatura_detController,
//     see_variablesController,
//     see_variables_detController,
//     serviciosController,
//     subcategoriasController,
//     sucurralesController,
//     susuariosController,
//     tecnicosController,
//     tra_categoriasController,
//     tra_cilindrajeController,
//     tra_cotizacionController,
//     tra_cotizacion_detController,
//     tra_cotizacion_totController,
//     tra_detallesController,
//     tra_fisicoController,
//     tra_grupposController,
//     tra_marcasController,
//     tra_matriculasController,
//     tra_matriculas_carController,
//     tra_matriculas_detController,
//     tra_modelosController,
//     tra_movtosController,
//     tra_movtos_detController,
//     tra_movtos_totController,
//     tra_partesController,
//     tra_periodosController,
//     tra_plantillasController,
//     tra_plantillas_detController,
//     tra_posicionesController,
//     tra_procesosController,
//     tra_procesos_tiemposController,
//     tra_procesos_tiempos_coloresController,
//     tra_referenciasController,
//     tra_referencias_proveedorController,
//     tra_saldosController,
//     tra_sjustesController,
//     tra_tipo_motorController,
//     tra_tipos_vehController,
//     tra_ubicacionesController,
//     usuariosController,
//     usuarios1Controller,
//     vehiculosController
//   ],
//   providers: [
//     ATRIBUTOSService,
//     CITASService,
//     CLAVESService,
//     COLECCIONESService,
//     CONFIGService,
//     CONFIGAUTOGESTIONService,
//     CONFIGBDService,
//     CONFIGCABEZAService,
//     CONFIGCAPTURAService,
//     CONFIGCAPTURADETService,
//     CONFIGCOTIZAService,
//     CONFIGDETALLEService,
//     CONFIGDOCUMENTOService,
//     CONFIGFORMULARIOService,
//     CONFIGKARDEXService,
//     CONFIGQRService,
//     CONFIGQRDETService,
//     CONFIGRELService,
//     CONFIGTABLEService,
//     CONFIGTARGETAService,
//     CONFIGUBICACIONService,
//     CONFIGVISTAService,
//     CONFIGVISTATService,
//     CONFIGZONASService,
//     CONFIG_CITASService,
//     CONFIG_ENCUESTAService,
//     CONTENIDOSService,
//     CONTENIDOS_CAPService,
//     CONTENIDOS_DETService,
//     CONTENIDOS_PROService,
//     CONTENIDOS_RECService,
//     CONTENIDOS_SUBService,
//     CONTENIDOS_TSKService,
//     CONTENIDOS_USRService,
//     CUESTIONARIOSService,
//     CUESTIONARIOS_PService,
//     CUESTIONARIOS_RService,
//     DEP_EQUIPOSService,
//     DETALLE_CELDASService,
//     DTN_TIEMPOService,
//     ENCUESTAService,
//     MERCADOService,
//     MERCADO_DETService,
//     NICHOSService,
//     OREPARACION1_2000Service,
//     OREPARACION2_2000Service,
//     PREGUNTASService,
//     PRESUPUESTOSService,
//     SYS_APPSService,
//     SYS_ROLESService,
//     SYS_ROL_CAMPOService,
//     SYS_SUBMENUSService,
//     TABLASService,
//     TABLAS_DETService,
//     TEMPORADASService,
//     VENCIMIENTOSService,
//     VERSIONESService,
//     VERSIONESDETService,
//     ZONASService,
//     categoriasService,
//     celdasService,
//     clientesService,
//     conceptosService,
//     consecutivosService,
//     datos_importadosService,
//     empresasService,
//     grupos_usuariosService,
//     kardexService,
//     motivosService,
//     motivos_anulacionService,
//     novimientosService,
//     novimientos_docService,
//     novimientos_vehService,
//     pedidosService,
//     pedidos_detService,
//     romboService,
//     see_costo_kwhService,
//     see_datosService,
//     see_formulasService,
//     see_medicionesService,
//     see_periodosService,
//     see_temperaturaService,
//     see_temperatura_detService,
//     see_variablesService,
//     see_variables_detService,
//     serviciosService,
//     subcategoriasService,
//     sucurralesService,
//     susuariosService,
//     tecnicosService,
//     tra_categoriasService,
//     tra_cilindrajeService,
//     tra_cotizacionService,
//     tra_cotizacion_detService,
//     tra_cotizacion_totService,
//     tra_detallesService,
//     tra_fisicoService,
//     tra_grupposService,
//     tra_marcasService,
//     tra_matriculasService,
//     tra_matriculas_carService,
//     tra_matriculas_detService,
//     tra_modelosService,
//     tra_movtosService,
//     tra_movtos_detService,
//     tra_movtos_totService,
//     tra_partesService,
//     tra_periodosService,
//     tra_plantillasService,
//     tra_plantillas_detService,
//     tra_posicionesService,
//     tra_procesosService,
//     tra_procesos_tiemposService,
//     tra_procesos_tiempos_coloresService,
//     tra_referenciasService,
//     tra_referencias_proveedorService,
//     tra_saldosService,
//     tra_sjustesService,
//     tra_tipo_motorService,
//     tra_tipos_vehService,
//     tra_ubicacionesService,
//     usuariosService,
//     usuarios1Service,
//     vehiculosService
//   ],
//   imports: [
//     TypeOrmModule.forFeature([
//       ATRIBUTOS,
//       CITAS,
//       CLAVES,
//       COLECCIONES,
//       CONFIG,
//       CONFIG_AUTOGESTION,
//       CONFIG_BD,
//       CONFIG_CABEZA,
//       CONFIG_CAPTURA,
//       CONFIG_CAPTURA_DET,
//       CONFIG_COTIZA,
//       CONFIG_DETALLE,
//       CONFIG_DOCUMENTO,
//       CONFIG_FORMULARIO,
//       CONFIG_KARDEX,
//       CONFIG_QR,
//       CONFIG_QR_DET,
//       CONFIG_REL,
//       CONFIG_TABLE,
//       CONFIG_TARGETA,
//       CONFIG_UBICACION,
//       CONFIG_VISTA,
//       CONFIG_VISTAT,
//       CONFIG_ZONAS,
//       CONFIG_CITAS,
//       CONFIG_ENCUESTA,
//       CONTENIDOS,
//       CONTENIDOS_CAP,
//       CONTENIDOS_DET,
//       CONTENIDOS_PRO,
//       CONTENIDOS_REC,
//       CONTENIDOS_SUB,
//       CONTENIDOS_TSK,
//       CONTENIDOS_USR,
//       CUESTIONARIOS,
//       CUESTIONARIOS_P,
//       CUESTIONARIOS_R,
//       DEP_EQUIPOS,
//       DETALLE_CELDAS,
//       DTN_TIEMPO,
//       ENCUESTA,
//       MERCADO,
//       MERCADO_DET,
//       NICHOS,
//       OREPARACION1_2000,
//       OREPARACION2_2000,
//       PREGUNTAS,
//       PRESUPUESTOS,
//       SYS_APPS,
//       SYS_ROLES,
//       SYS_ROL_CAMPO,
//       SYS_SUBMENUS,
//       TABLAS,
//       TABLAS_DET,
//       TEMPORADAS,
//       VENCIMIENTOS,
//       VERSIONES,
//       VERSIONES_DET,
//       ZONAS,
//       categorias,
//       celdas,
//       clientes,
//       conceptos,
//       consecutivos,
//       datos_importados,
//       empresas,
//       grupos_usuarios,
//       kardex,
//       motivos,
//       motivos_anulacion,
//       novimientos,
//       novimientos_doc,
//       novimientos_veh,
//       pedidos,
//       pedidos_det,
//       rombo,
//       see_costo_kwh,
//       see_datos,
//       see_formulas,
//       see_mediciones,
//       see_periodos,
//       see_temperatura,
//       see_temperatura_det,
//       see_variables,
//       see_variables_det,
//       servicios,
//       subcategorias,
//       sucurrales,
//       susuarios,
//       tecnicos,
//       tra_categorias,
//       tra_cilindraje,
//       tra_cotizacion,
//       tra_cotizacion_det,
//       tra_cotizacion_tot,
//       tra_detalles,
//       tra_fisico,
//       tra_gruppos,
//       tra_marcas,
//       tra_matriculas,
//       tra_matriculas_car,
//       tra_matriculas_det,
//       tra_modelos,
//       tra_movtos,
//       tra_movtos_det,
//       tra_movtos_tot,
//       tra_partes,
//       tra_periodos,
//       tra_plantillas,
//       tra_plantillas_det,
//       tra_posiciones,
//       tra_procesos,
//       tra_procesos_tiempos,
//       tra_procesos_tiempos_colores,
//       tra_referencias,
//       tra_referencias_proveedor,
//       tra_saldos,
//       tra_sjustes,
//       tra_tipo_motor,
//       tra_tipos_veh,
//       tra_ubicaciones,
//       usuarios,
//       usuarios1,
//       vehiculos
//     ])
//   ]
// })
// export class MacrollantasModule {}
